[general]
# Set your preferred provider: "groq" or "openai"
llm_provider = "groq"

[groq]
api_key = "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"
model_name = "llama-3.3-70b-versatile"

[openai]
api_key = "YOUR_OPENAI_API_KEY"
model_name = "gpt-3.5-turbo"

[email]
sender_email = "manikanta_tumpilli@srmap.edu.in"
sender_password = "dcbw opti nipg deue"
smtp_server = "smtp.gmail.com"
smtp_port = 587
